In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits=load_digits()

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.2)

In [6]:
lr=LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

0.9555555555555556

In [7]:
svm=SVC(gamma='auto')
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.4444444444444444

In [10]:
rf=RandomForestClassifier(n_estimators=30)
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9694444444444444

In [13]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=5)
kf

KFold(n_splits=5, random_state=None, shuffle=False)

In [15]:
for train_index, test_index in kf.split([1,2,3,4,5,6]):
    print(train_index, test_index)

[2 3 4 5] [0 1]
[0 1 3 4 5] [2]
[0 1 2 4 5] [3]
[0 1 2 3 5] [4]
[0 1 2 3 4] [5]


In [16]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [17]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [18]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [19]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [20]:
scores_rf

[0.9348914858096828, 0.9432387312186978, 0.9165275459098498]

In [22]:
from sklearn.model_selection import cross_val_score

In [24]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'),digits.data,digits.target,cv=5)

array([0.92222222, 0.88333333, 0.95264624, 0.95821727, 0.89415042])

In [25]:
cross_val_score(SVC(gamma='auto'),digits.data,digits.target,cv=5)

array([0.41111111, 0.45      , 0.454039  , 0.44846797, 0.47910864])

In [26]:
cross_val_score(RandomForestClassifier(n_estimators=30),digits.data,digits.target,cv=5)

array([0.925     , 0.9       , 0.95543175, 0.9637883 , 0.91086351])

In [28]:
import numpy as np

In [29]:
score_1=cross_val_score(RandomForestClassifier(n_estimators=5),digits.data,digits.target,cv=5)
np.average(score_1)

0.8737109254100897

In [30]:
score_2=cross_val_score(RandomForestClassifier(n_estimators=10),digits.data,digits.target,cv=5)
np.average(score_2)

0.9104255648406067

In [31]:
score_3=cross_val_score(RandomForestClassifier(n_estimators=20),digits.data,digits.target,cv=5)
np.average(score_3)

0.9182203652120087

In [32]:
score_4=cross_val_score(RandomForestClassifier(n_estimators=20),digits.data,digits.target,cv=5)
np.average(score_4)

0.9232265552460539

In [33]:
score_5=cross_val_score(RandomForestClassifier(n_estimators=30),digits.data,digits.target,cv=5)
np.average(score_5)

0.9282234602290312

In [34]:
score_6=cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target,cv=5)
np.average(score_6)

0.9299133395233674